language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  user: chermed
  password:
    secure: DPO87OEmx5uhQY0wBwqSy7d0KbZCQH3JG5cUZ2cGrc/OHrVADezw6RYo1kQmNlRy3LJTPRcpVZFjzXQKeZUkNDkTfsFSssj/loj9b87BVz5MYnmzXoZRvgSnFlDJUiAkkQ0DEg9KX9xHXA6J99zs4v6vx4m8L/2yB7ThM7K3AhpR7Pes0soJwHk2MQWc1xsU/hKxwrNp3QMKhM3rvu8mjhmEwj8k8Mzdkqdhflorz/L/QwQWa1YsJM1EtoRM1FwNdKfXqBDFxkoMYvkCA4qIFqnA7G3CCQw6RXv9TecrgXykiEF6HDpgsznorlGubqyG1T1zciuEjVnMXNVo8x20gUC3G1sgPDBMvbEghRRxWDmd84oI8GMNgQqv/J4KJQaACXtce/OA4p8zTlAbbWD+Er7nv3BVH4yWQxdno/OWZINU5pHBybzc95HaNEOtkacH/l4hfQf7QRqbVzLu6V+mmcZQw168bpuGyCmtQsbdQ81E9YnrX5q+OhuMtXMISxBw0nH9CMyG52cyMxtHumlkUanxtiEsqo1A+l3VfgLZAfkoILtskcOddgzSFc8KhyqqbYZiYcsYE9+fWJMbRdNZzHvlbKescL7IOZz5NtupMSNL9B1/rpNUJd8ZU+Kp6XdfelUMAPFtQNKb3HULIcM9aRI83LcLvBvqVYpsrwQXXNw=
  on:
    distributions: sdist bdist_wheel
    repo: chermed/odootools
