language: python
python: 3.5
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: chermed
  password:
    secure: kmoNSVetcr3gO1xR1/Xq+ml9nKeG0crb/8Sz/9NEaJGFyeiDAzk3KmJyDhc4PfE3DkbRpRHDSgGDmQp73/eaiN1D4YK7qmjbhMzWsITRB+SIN9ptwIvh9yYEyUpkCFhDsjuCMtVnwEtpjUYsPYOKLVNKbK7eUX5EkWJX7XQDvcJ/3ga9TlOfMTwmpQx7BlsJHms3ttBoS8/VMBYssKQE6ifhdTL2fBohyNW2bI28UsaHkimHxSKCw/YfrzoyqdUC4B9D9FZiA47RRCrFGtxT62o7jpsqOWHqDQHBDZl2Nvro+NcxKlcnT1rN4hTRHb3qZlNuNtEQCwwgUzdezbO4dUlo/HyhH6Aolw93oP7afdW2RLQE5YoSJCPSYu8eK+LTMvIrDGj5Nc4y9w9isurKtHsm/Tfoua/5nvjph9L2URLZtyKZsVqNAPuVMUAoQTuhILu6nJFDZ7kR8wmDpA516LbTJG7gpYTkB7H5Sw7u+cNM893iRBQ4uzyfDxH6KaoIMb8qnBIqFbutKSyeZ6IHgPajcBrFpZblSB6qbedcklyP27aAiFVRUSe1aBpd9irYNNeE8iwsDmGmTKAtIyhHLBpBzkvj0U1QMhCnPBheC7pPkwi6VvYOPnOMvuKvqEubFi45ptTcFesRxxSKb7DcSGxyh0j3XsVgXwMyDAJRVYo=
  on:
    repo: chermed/odootools
